# Unique name for this workflow
name: Deploy to Prod

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Jobs to be executed
jobs:
  deploy-to-org:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      # Checkout the source code
      - name: "Checkout source code"
        uses: actions/checkout@v4

      # Install Salesforce CLI
      - name: "Install Salesforce CLI"
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sf --version

      # Store secret for dev hub
      - name: "Populate auth file with DEVHUB_SFDX_URL secret"
        shell: bash
        run: |
          echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
          if [ $secretFileSize == 1 ]; then
              echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
              exit 1;
          fi

      # Authenticate dev hub
      - name: "Authenticate Dev Hub"
        run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d

      # Deploy source to scratch org
      - name: "Validate Deployment"
        run: sf project deploy start --dry-run --test-level RunAllTestInOrg

      - name: Deploy to Org
        run: sf project deploy start --test-level RunAllTestsInOrg
